### PR TITLE
Battery Interface Module v2.0.0-beta

### PR DESCRIPTION
**Pull request by aaronbeekay**
# v2.0.0
Battery Interface Module v2.0.0-beta is a complete redesign for RW-3.

## Major changes
* Redesign to be a 24-cell monitor (not 36).
* Remove onboard balancing circuit.
* Remove CAN auto-termination circuit and replace with termination switch.
* Updated CAN communications circuit for improved robustness to electromagnetic noise.
* Reduce size and height to integrate with RW-3 battery pack.

### CODE REVIEW

**Comment by lordnathan0** [comment]
- It seems a bit odd that filtering caps on the Battery measurement lines are connected to VC0 of each BQ instead of the next cell down
- The communication lines are much longer...this scares me. Though I understand there isn't much you can do
- The isolation distance between the BQ ground planes look really small. 
- The thermal pads on the BQs are different :expressionless:

**Comment by aaronbeekay** [comment]
@lordnathan0 -

* The filter cap change is intentional - according to TI, that arrangement provides better performance.
* Not much to be done about the comm lines. For what it's worth, the comm lines on the EVM and on other designs that I've seen are at least that long.
* I calculated minimum clearance distances by IEC 60950-1. Specifically, sections 2.10.5.5, "Cemented Joints", and 2.10.6.3, "Insulation between Conductors on the Same Inner Surface of a Printed Circuit Board", are relevant to the ground plane clearances. With a max. working voltage of 50 Vdc, the minimum clearance is ~0.1 mm, which I satisfy.
* Variety is the spice of life.

**Comment by aaronbeekay** [comment]
If it's OK with folks, I'm going to move the conversation here to reduce the amount of email tracking we have to do.

@Victorb101 - point taken on the screwhead clearances. 

* I've moved all traces outside of the clearance radius for an M2 machine screw. 
* I also added the silkscreen label for the +5V test point - good catch, apparently I missed that twice in a row.

@polbrod: I'm surprised that you don't think the slots for those tabs will print well - as designed, the tabs only extend 1.5 mm past the M12 mating plane, and the tolerances on the slot height do not need to be tight. Do you think a 2mm deep notch in a wall will be an issue for our printers? The through hole for the CAN connector, just above those notches, is about as wide, and a through hole.

>This will scrape your board components against the mounting standoffs

I assumed that the board would be inserted at an angle. The M12 clearance drill is slightly oversize in the mechanical drawings for that reason.

>You still have the same number of fasteners (3 screws to fix the board down)

Just to make sure we're on the same page, there are only two screws to fasten the BIM down as currently planned: the third hole, in the center of the PCB, is for a plastic peg board support.

bim_enclosure_bosses

**Comment by polbrod** [comment]
@aaronbeekay 

The width isn't the problem. Bad prints usually come from a lot of overhung, unsupported material being put down at once. The sketch below might help: 

3d_print_sag_demonstration

The red lines in the sketches represent overhung material in both features. As you can see in the large hole, the size of the overhung sections are small compared to that of the large slot. That's the reason we can print large holes but not large slots in the sides of parts. 

The M12 oversize hole isn't big enough to insert the board at an angle. A typical M12 oversize hole is 13.4mm and your M12 connector is very long. 

I can make the third fixture a board support if you'd like. Even with two threaded holes, I think your concerns won't come up. We fixed the BIMS by 2 screws and a connector last year and didn't seem to have any of those issues, as far as I know. 

What would be the reason behind running the BIMS with no CAN connector?

**Comment by aaronbeekay** [comment]
@polbrod per our conversation on IM - removed mounting tabs. (There are still bumps on that side of the board but they shouldn't hit the wall.)

@Victorb101, @polbrod, @lordnathan0 - do you see any other outstanding issues before we get the first run of this board manufactured?

**Comment by Victorb101** [comment]
@aaronbeekay Will your testing board (with pogo pins) sit above the top of
the MicroClasp connectors?  If not then you won't be able to reach TP3 and
maybe TP9 where they are currently located.  Thats the only thing I see
atm, looks fab.

**Comment by Victorb101** [comment]
@aaronbeekay I would also recommend putting the HV symbol on the bottom silk.  And a board title would be great even if it is tiny.

**Comment by aaronbeekay** [comment]
@Victorb101 Pogo pins should be good where they are - the test board won't extend over the MicroClasp connectors.

There's already a board label on the bottom side (you might not be able to see it in the PDFs because it's white). I added the HV symbol down there too, good catch.

**Comment by Victorb101** [comment]
@aaronbeekay  I still think TP3 is too close to the Microclasp.  You
couldn't physically have a pogo pin mounted to the test board touch this
because the Microclasp interferes.  This could be moved right on the other
side of the trace.

Victor Brechbill | The Ohio State University
p: 614-556-2461 | e: victorbrechbill@gmail.com

**Comment by aaronbeekay** [comment]
@Victorb101 It clears OK - the white circle around TP3 is the maximum diameter of the pogo pin.

image

If I regenerate the Gerbers I'll move it up anyway.

**Pull request merged**
